<a href="https://colab.research.google.com/github/tudaysai45/Minor_project1/blob/main/minorproject1da_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DA_DS PROJECT-1

In [ ]:
import numpy as np
from datetime import datetime, timedelta

print("=" * 65)
print(" GROUP DNA WHATSAPP ANALYZER")
print("=" * 65)

 GROUP DNA WHATSAPP ANALYZER


In [ ]:
FILE_NAME = "/content/whatsappchat.csv"

try:
    file = open(FILE_NAME, "r", encoding="utf-8-sig")
except FileNotFoundError:
    try:
        file = open("/content/whatsappchatcsv", "r", encoding="utf-8-sig")
        FILE_NAME = "/content/whatsappchatcsv"
    except FileNotFoundError:
        file = open("/content/mywhatsappchat.csv", "r", encoding="utf-8-sig")
        FILE_NAME = "/content/mywhatsappchat.csv"

lines = file.readlines()
file.close()

print("File loaded successfully!")
print("File:", FILE_NAME)
print("Total lines:", len(lines))

File loaded successfully!
File: /content/whatsappchat.csv
Total lines: 3001


In [ ]:
messages = []

for line in lines[1:]:
    line = line.strip()

    if line == "":
        continue

    parts = line.split(",", 3)

    if len(parts) == 4:
        date = parts[0].strip()
        time = parts[1].strip()
        sender = parts[2].strip()
        text = parts[3].strip()

        messages.append({
            "date": date,
            "time": time,
            "sender": sender,
            "text": text
        })

print("Messages parsed:", len(messages))

Messages parsed: 3000


In [ ]:
valid_messages = []

for msg in messages:

    try:
        msg["timestamp"] = datetime.strptime(
            msg["date"] + " " + msg["time"],
            "%d/%m/%Y %H:%M"
        )

        valid_messages.append(msg)

    except ValueError:
        pass

messages = valid_messages

print("Valid messages:", len(messages))

for msg in messages[:5]:
    print(
        msg["date"],
        msg["time"],
        "-",
        msg["sender"],
        ":",
        msg["text"]
    )

Valid messages: 3000
01/01/2026 07:21 - Babu : Super bro
01/01/2026 13:31 - Babu : Dinner ayinda?
01/01/2026 14:24 - Babu : Done ra
01/01/2026 15:17 - Loki : Coming now
01/01/2026 15:48 - Bhen : Nice one


In [ ]:
participants = []
message_count = {}

for msg in messages:

    person = msg["sender"]

    if person not in participants:
        participants.append(person)

    message_count[person] = message_count.get(person, 0) + 1

participants = sorted(participants)

ranking = sorted(
    message_count.items(),
    key=lambda x: x[1],
    reverse=True
)

print("=" * 65)
print("PARTICIPANTS:", len(participants))
print("=" * 65)

for person, count in ranking:
    print(f"{person:<15} : {count} messages")

PARTICIPANTS: 21
Balu            : 166 messages
Loki            : 154 messages
Babu            : 153 messages
Sai             : 153 messages
Kiran           : 147 messages
Bhanu           : 146 messages
Harshit         : 145 messages
Pranav          : 144 messages
Nikhil          : 142 messages
Pavan           : 142 messages
Manoj           : 142 messages
Sanjay          : 142 messages
Akash           : 141 messages
Rakesh          : 141 messages
Bhen            : 139 messages
Yuvaraj         : 139 messages
Alex            : 139 messages
Abhinash        : 136 messages
Babblu          : 133 messages
Deepak          : 132 messages
Harsha          : 124 messages


In [ ]:
date_count = {}

for msg in messages:

    day = msg["timestamp"].date()

    date_count[day] = date_count.get(day, 0) + 1

if date_count:

    first_date = min(date_count)
    last_date = max(date_count)

    busiest_day = max(
        date_count,
        key=date_count.get
    )

    print("=" * 65)
    print("DATE ANALYSIS")
    print("=" * 65)

    print("First Date :", first_date)
    print("Last Date  :", last_date)
    print(
        "Total Days :",
        (last_date - first_date).days + 1
    )
    print(
        "Busiest Day:",
        busiest_day
    )
    print(
        "Messages   :",
        date_count[busiest_day]
    )

else:
    print("No valid date data found.")

DATE ANALYSIS
First Date : 2026-01-01
Last Date  : 2026-08-23
Total Days : 235
Busiest Day: 2026-05-09
Messages   : 24


In [ ]:
hour_count = {}

for msg in messages:

    hour = msg["timestamp"].hour

    hour_count[hour] = hour_count.get(hour, 0) + 1

if hour_count:

    busiest_hour = max(
        hour_count,
        key=hour_count.get
    )

    print("=" * 65)
    print("HOURLY ACTIVITY")
    print("=" * 65)

    for hour in sorted(hour_count):
        print(
            f"{hour:02d}:00 - "
            f"{hour_count[hour]} messages"
        )

    print(
        "\nBusiest Hour:",
        f"{busiest_hour:02d}:00"
    )

HOURLY ACTIVITY
07:00 - 46 messages
08:00 - 44 messages
09:00 - 76 messages
10:00 - 123 messages
11:00 - 147 messages
12:00 - 148 messages
13:00 - 146 messages
14:00 - 186 messages
15:00 - 262 messages
16:00 - 239 messages
17:00 - 251 messages
18:00 - 325 messages
19:00 - 254 messages
20:00 - 231 messages
21:00 - 189 messages
22:00 - 188 messages
23:00 - 145 messages

Busiest Hour: 18:00


In [ ]:
people = sorted(participants)

person_index = {}

for i in range(len(people)):
    person_index[people[i]] = i

activity = np.zeros(
    (len(people), 24),
    dtype=int
)

for msg in messages:

    row = person_index[msg["sender"]]
    hour = msg["timestamp"].hour

    activity[row][hour] += 1

print("=" * 65)
print("NUMPY ACTIVITY MATRIX")
print("=" * 65)

print("Shape:", activity.shape)
print(activity)

NUMPY ACTIVITY MATRIX
Shape: (21, 24)
[[ 0  0  0  0  0  0  0  1  0  5  9 11  3  3 11 11  7  9 15 11  8 10 12 10]
 [ 0  0  0  0  0  0  0  2  5  2  2  9  7  7  9  9  8 15 12 14  9  6 12 13]
 [ 0  0  0  0  0  0  0  4  4  4  9  4  4  2  7 17 11  8 17 10 13 10  9  6]
 [ 0  0  0  0  0  0  0  3  1  4 12  7  9  7 10  9  7 12 10 10 12 10  7  3]
 [ 0  0  0  0  0  0  0  1  0  3  5  6  7  9 16 10 15 13 19  9 10 11 14  5]
 [ 0  0  0  0  0  0  0  2  1  4  4  6  6  7 10 23 15 15 18 14 16  7 14  4]
 [ 0  0  0  0  0  0  0  1  4  3  8 10  5  7  9 10 17  9 14 16 11  5 10  7]
 [ 0  0  0  0  0  0  0  3  2  2  5  6 11  8  7 11 10 17 14  7  9 10  9  8]
 [ 0  0  0  0  0  0  0  6  2  5  2  5  4  8  8 16 11 15 16 13  6  5  6  4]
 [ 0  0  0  0  0  0  0  2  2  6  4  7  4  4 10 15 11  6 13  9 10 10  6  5]
 [ 0  0  0  0  0  0  0  1  2  1  5  4  9  8  7 12 10 15 27  7 10 13  8  6]
 [ 0  0  0  0  0  0  0  2  3  3  8  9 10  7 10 14 12  8 13 10  5 15  8 10]
 [ 0  0  0  0  0  0  0  1  3  5  5  6  8  6 11 10  8 16 20 13 

In [ ]:
print("=" * 65)
print("                    ACTIVITY HEATMAP")
print("=" * 65)

print("             ", end="")

for hour in range(24):
    print(f"{hour:02d} ", end="")

print()

for i in range(len(people)):

    print(f"{people[i]:<12}", end="")

    row_max = np.max(activity[i])

    for value in activity[i]:

        if value == 0:
            symbol = "."
        elif row_max > 0 and value <= row_max * 0.25:
            symbol = "░"
        elif row_max > 0 and value <= row_max * 0.50:
            symbol = "▒"
        else:
            symbol = "█"

        print(f"{symbol}  ", end="")

    print()

                    ACTIVITY HEATMAP
             00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Abhinash    .  .  .  .  .  .  .  ░  .  ▒  █  █  ░  ░  █  █  ▒  █  █  █  █  █  █  █  
Akash       .  .  .  .  .  .  .  ░  ▒  ░  ░  █  ▒  ▒  █  █  █  █  █  █  █  ▒  █  █  
Alex        .  .  .  .  .  .  .  ░  ░  ░  █  ░  ░  ░  ▒  █  █  ▒  █  █  █  █  █  ▒  
Babblu      .  .  .  .  .  .  .  ░  ░  ▒  █  █  █  █  █  █  █  █  █  █  █  █  █  ░  
Babu        .  .  .  .  .  .  .  ░  .  ░  ▒  ▒  ▒  ▒  █  █  █  █  █  ▒  █  █  █  ▒  
Balu        .  .  .  .  .  .  .  ░  ░  ░  ░  ▒  ▒  ▒  ▒  █  █  █  █  █  █  ▒  █  ░  
Bhanu       .  .  .  .  .  .  .  ░  ░  ░  ▒  █  ▒  ▒  █  █  █  █  █  █  █  ▒  █  ▒  
Bhen        .  .  .  .  .  .  .  ░  ░  ░  ▒  ▒  █  ▒  ▒  █  █  █  █  ▒  █  █  █  ▒  
Deepak      .  .  .  .  .  .  .  ▒  ░  ▒  ░  ▒  ░  ▒  ▒  █  █  █  █  █  ▒  ▒  ▒  ░  
Harsha      .  .  .  .  .  .  .  ░  ░  ▒  ▒  ▒  ▒  ▒  █  █  █  ▒  █  █  █  █  ▒  ▒  
Harshit     .  .  .  .  .  

In [ ]:
stop_words = {
    "the", "is", "a", "an", "and", "or",
    "to", "of", "in", "on", "for", "it",
    "this", "that", "you", "we", "are",
    "was", "be", "am", "i", "me", "my"
}

word_count = {}

for msg in messages:

    words = msg["text"].lower().split()

    for word in words:

        word = word.strip(".,!?;:'\"()[]{}")

        if word == "":
            continue

        if word in stop_words:
            continue

        word_count[word] = word_count.get(word, 0) + 1

top_words = sorted(
    word_count.items(),
    key=lambda x: x[1],
    reverse=True
)[:10]

print("=" * 65)
print("TOP 10 WORDS")
print("=" * 65)

for word, count in top_words:
    print(f"{word:<20} : {count}")

TOP 10 WORDS
bro                  : 410
send                 : 185
done                 : 179
good                 : 174
everyone             : 172
okay                 : 171
plan                 : 132
wait                 : 130
ra                   : 128
coming               : 123


In [ ]:
response_times = {}

for person in participants:
    response_times[person] = []

previous = None

for msg in messages:

    if previous is not None:

        if msg["sender"] != previous["sender"]:

            gap = (
                msg["timestamp"]
                - previous["timestamp"]
            ).total_seconds()

            if gap >= 0 and gap <= 86400:

                response_times[
                    msg["sender"]
                ].append(gap)

    previous = msg

average_response = {}

for person in participants:

    gaps = response_times[person]

    if len(gaps) > 0:
        average_response[person] = (
            sum(gaps) / len(gaps)
        )
    else:
        average_response[person] = 0

print("=" * 65)
print("RESPONSE SPEED")
print("=" * 65)

for person in participants:

    minutes = average_response[person] / 60

    print(
        f"{person:<15} : "
        f"{minutes:.1f} minutes"
    )

RESPONSE SPEED
Abhinash        : 95.7 minutes
Akash           : 105.5 minutes
Alex            : 133.0 minutes
Babblu          : 103.9 minutes
Babu            : 92.5 minutes
Balu            : 119.3 minutes
Bhanu           : 126.0 minutes
Bhen            : 90.5 minutes
Deepak          : 108.9 minutes
Harsha          : 122.7 minutes
Harshit         : 101.5 minutes
Kiran           : 172.2 minutes
Loki            : 116.7 minutes
Manoj           : 88.3 minutes
Nikhil          : 111.8 minutes
Pavan           : 106.2 minutes
Pranav          : 115.5 minutes
Rakesh          : 99.6 minutes
Sai             : 125.2 minutes
Sanjay          : 93.9 minutes
Yuvaraj         : 122.1 minutes


In [ ]:
all_days = []

if date_count:

    current = first_date

    while current <= last_date:

        all_days.append(current)

        current += timedelta(days=1)

active_days = {}

for person in participants:
    active_days[person] = set()

for msg in messages:

    active_days[
        msg["sender"]
    ].add(
        msg["timestamp"].date()
    )

silent_streak = {}

for person in participants:

    current_streak = 0
    maximum_streak = 0

    for day in all_days:

        if day in active_days[person]:

            current_streak = 0

        else:

            current_streak += 1

            if current_streak > maximum_streak:
                maximum_streak = current_streak

    silent_streak[person] = maximum_streak

print("=" * 65)
print("THE GHOST — LONGEST SILENT STREAK")
print("=" * 65)

for person, days in sorted(
    silent_streak.items(),
    key=lambda x: x[1],
    reverse=True
):

    print(
        f"{person:<15} : "
        f"{days} silent days"
    )

THE GHOST — LONGEST SILENT STREAK
Harsha          : 11 silent days
Bhanu           : 9 silent days
Bhen            : 9 silent days
Harshit         : 9 silent days
Kiran           : 9 silent days
Pranav          : 9 silent days
Yuvaraj         : 9 silent days
Akash           : 8 silent days
Babblu          : 8 silent days
Abhinash        : 7 silent days
Babu            : 7 silent days
Deepak          : 7 silent days
Loki            : 7 silent days
Alex            : 6 silent days
Balu            : 6 silent days
Manoj           : 6 silent days
Sai             : 6 silent days
Pavan           : 5 silent days
Rakesh          : 5 silent days
Nikhil          : 4 silent days
Sanjay          : 4 silent days


In [ ]:
archetypes = {}

funny_words = [
    "haha", "hahaha", "lol",
    "lmao", "rofl", "lmfao"
]

for person in participants:

    entertainer = 0
    drama = 0
    night = 0
    storyteller_words = 0

    person_msgs = []

    for msg in messages:

        if msg["sender"] == person:

            person_msgs.append(msg)

            text = msg["text"]
            lower = text.lower()

            storyteller_words += len(text.split())

            for word in funny_words:

                if word in lower:
                    entertainer += 1

            if len(text) >= 3 and text.isupper():
                drama += 1

            if text.count("!") >= 2:
                drama += 1

            hour = msg["timestamp"].hour

            if hour >= 23 or hour <= 4:
                night += 1

    if len(person_msgs) > 0:
        storyteller = (
            storyteller_words /
            len(person_msgs)
        )
    else:
        storyteller = 0

    scores = {
        "THE GHOST": silent_streak.get(person, 0),
        "THE ENTERTAINER": entertainer,
        "THE DRAMA QUEEN": drama,
        "THE NIGHT OWL": night,
        "THE STORYTELLER": storyteller
    }

    archetypes[person] = max(
        scores,
        key=scores.get
    )

print("=" * 65)
print("PERSONALITY ARCHETYPES")
print("=" * 65)

for person in participants:

    print(
        f"{person:<15} → "
        f"{archetypes[person]}"
    )

PERSONALITY ARCHETYPES
Abhinash        → THE NIGHT OWL
Akash           → THE NIGHT OWL
Alex            → THE GHOST
Babblu          → THE GHOST
Babu            → THE GHOST
Balu            → THE ENTERTAINER
Bhanu           → THE GHOST
Bhen            → THE GHOST
Deepak          → THE GHOST
Harsha          → THE GHOST
Harshit         → THE GHOST
Kiran           → THE NIGHT OWL
Loki            → THE NIGHT OWL
Manoj           → THE GHOST
Nikhil          → THE NIGHT OWL
Pavan           → THE NIGHT OWL
Pranav          → THE GHOST
Rakesh          → THE NIGHT OWL
Sai             → THE NIGHT OWL
Sanjay          → THE NIGHT OWL
Yuvaraj         → THE GHOST


Final Report


In [ ]:
print("\n")
print("╔" + "═" * 63 + "╗")
print("║" + "             GROUPDNA FINAL REPORT".center(63) + "║")
print("╚" + "═" * 63 + "╝")

print("\nGROUP OVERVIEW")
print("-" * 50)

print("Total Messages :", len(messages))
print("Participants   :", len(participants))

if date_count:
    print("First Date     :", first_date)
    print("Last Date      :", last_date)
    print("Total Days     :", (last_date - first_date).days + 1)
    print("Busiest Day    :", busiest_day)
    print("Busiest Hour   :", f"{busiest_hour:02d}:00")

print("\nTOP CONTRIBUTORS")
print("-" * 50)

for person, count in ranking[:5]:
    print(f"{person:<15} : {count}")

print("\nTOP WORDS")
print("-" * 50)

for word, count in top_words:
    print(f"{word:<15} : {count}")

print("\nPERSONALITY")
print("-" * 50)

for person in participants:
    print(
        f"{person:<15} → "
        f"{archetypes[person]}"
    )

print("\n" + "═" * 65)
print("             GROUPDNA COMPLETE")
print("═" * 65)



╔═══════════════════════════════════════════════════════════════╗
║                            GROUPDNA FINAL REPORT              ║
╚═══════════════════════════════════════════════════════════════╝

GROUP OVERVIEW
--------------------------------------------------
Total Messages : 3000
Participants   : 21
First Date     : 2026-01-01
Last Date      : 2026-08-23
Total Days     : 235
Busiest Day    : 2026-05-09
Busiest Hour   : 18:00

TOP CONTRIBUTORS
--------------------------------------------------
Balu            : 166
Loki            : 154
Babu            : 153
Sai             : 153
Kiran           : 147

TOP WORDS
--------------------------------------------------
bro             : 410
send            : 185
done            : 179
good            : 174
everyone        : 172
okay            : 171
plan            : 132
wait            : 130
ra              : 128
coming          : 123

PERSONALITY
--------------------------------------------------
Abhinash        → THE NIGHT OWL
Akash 